### ISSUE TITLE
RadialSlider: Multitouch Support

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#231]
<sup>Issue created by Ryan H as [Bitbucket Issue #&#8203;231](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/231) on 2018.04.12 02:08.</sup>
Is there a way to have multiple radial sliders work independently with 2 or more touches on the screen?

Currently, when 2 fingers are used on 2 radial sliders (one finger on each slider), they conflict with one another.

Thanks you!

**Comment by 2Hadolphin** [comment]
We had a same script GUID for Modern UI Pack and uiextensions.

`GUID [803cebee00d5c504e930205383017dc1] for asset 'Packages/com.unity.uiextensions/Runtime/Scripts/Controls/Sliders/RadialSlider.cs' conflicts with:
  'Assets/../Modern UI Pack/Scripts/Slider/RadialSlider.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
`
