### ISSUE TITLE
RFI: UI Line Renderer RectTransform position

### ISSUE THREAD

**Issue by hugoymh** [Unity-UI-Extensions/com.unity.uiextensions#478]
While using UILineRenderer Component, it's very easy to trigger the Log Warning:

> `A Line Renderer component should be on a RectTransform positioned at (0,0,0), do not use in child Objects.
> For best results, create separate RectTransforms as children of the canvas positioned at (0,0) for a UILineRenderer and do not move.`

A peek into the source code reveals that the condition for this warning is:

> `if (transform.GetComponent<RectTransform>().position != Vector3.zero)`

which means it should be putting at _World Position_ (0, 0, 0).

Would like to ask if this is really the intended suggestion? I feel that the condition should be at _Local Position_ (0, 0, 0) instead. Seems very unintuitive to maintain its world position at zero while it's very likely the Line Renderer Component could be layers deep inside the RectTransform hierarchy.

**Comment by SimonDarksideJ** [comment]
The answer is simply because the pivot point inside a RectTransform uses "LocalPosition" as a reference.
Due to the way that Unity calculates positions within a RectTransform, you get huge variances trying to compensate for different pivot points.

If you have a suggestion or PR to help improve this, we are welcome to contributions.

P.S. Feel free to clone the repository locally, remove the restriction and then play with the positions to see the unintended effects.

**Comment by hugoymh** [comment]
Thanks for the comment, I've looked into other reported issues and it seems that this warning is related to [Issue#440](https://github.com/Unity-UI-Extensions/com.unity.uiextensions/issues/440).

I've made a PR mainly changing the `UILineConnector`. I hope this can address both of these questions :)

**Comment by SimonDarksideJ** [comment]
Resolved with #480
