### ISSUE TITLE
UIParticleSystem does not works on Standalone Build

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#99]
<sup>Issue created by &lt;unknown&gt; as [Bitbucket Issue #&#8203;99](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/99) on 2016.12.06 19:05.</sup>
On Editor it works, but on Standalone build it fails with error :

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Material:Internal_CreateWithShader (UnityEngine.Material,UnityEngine.Shader)
  at UnityEngine.Material..ctor (UnityEngine.Shader shader) [0x00000] in <filename unknown>:0 
  at UnityEngine.UI.Extensions.UIParticleSystem.Initialize () [0x00000] in <filename unknown>:0 
  at UnityEngine.UI.Extensions.UIParticleSystem.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.Object:Internal_CloneSingle(Object)
UnityEngine.Object:Instantiate(Object)

**Comment by ja179053** [comment]
Can confirm this package is deprecated. New versions of Unity will render the particles as squares instead of particles, becuase of the way UIParticleSystem renders them. The above procedure will only work for particles within the main camera's frustrum. To add a particle system to UI either create your particles in world space, or add to a canvas with "Screen Space - Camera".
Edit: you can also use shadergraph to render particles.

**Comment by SimonDarksideJ** [comment]
> Can confirm this package is deprecated. New versions of Unity will render the particles as squares instead of particles, becuase of the way UIParticleSystem renders them. The above procedure will only work for particles within the main camera's frustrum. To add a particle system to UI either create your particles in world space, or add to a canvas with "Screen Space - Camera". Edit: you can also use shadergraph to render particles.

The package is not deprecated, and I've not made any statements to that effect.

If you are experiencing a new issue, please log a new request and I can take a look it.  If you also have suggestions or fixes for improvement, we also accept PR's.
Thanks for your support
